# Generated by Django 3.2.4 on 2024-04-12 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
